var brands = [
    // https://qz.com/1039381/amazon-owns-a-whole-collection-of-secret-brands/
    "AmazonBasics",
    "Arabella",
    "Beauty Bar",
    //"Denali",
    "Franklin & Freeman",
    "Happy Belly",
    "James & Erin",
    "Lark & Ro",
    "Mae",
    "Mama Bear",
    "Myhabit",
    "North Eleven",
    "NuPro",
    "Pike Street",
    "Pinzon",
    "Scout + Ro",
    "Single Cow Burger",
    "Small Parts",
    "Smart is Beautiful",
    "Strathwood",
    "Bloom Street",
    "Concrete New York",
    "Familyhood",
    //"Find",
    "GT Prime",
    "Instant Pretty",
    "RV Me",
    //"Single",
    "Skate Creek",
    "Sweatermen",
    "Goodthreads",
    "The Fix",
    "Coastal Blue",
    "Ella Moon",
    "Ocean Blues",
    "Paris Sunday",
    "Presto!",
    "Rebel Canyon",
    "Smitten",
]
